#!/usr/bin/env python3
from pathlib import Path
from chainlit.cli import run_chainlit
from chainlit.config import config


def main():
    """Run from ROS"""
    # TODO: Add chainlit option handling via ROS

    root_path = Path(__file__).parent / Path("app.py")

    # Set general config options
    config.run.headless = True
    config.project.enable_telemetry = False
    config.root = str(root_path.parent)

    # Set audio config options
    config.features.audio.sample_rate = 16000  # type: ignore
    config.features.audio.initial_silence_timeout = 2000  # type: ignore
    config.features.audio.silence_timeout = 1000  # type: ignore

    run_chainlit(str(root_path))


if __name__ == "__main__":
    main()
