repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-docstring-first
    -   id: check-toml
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.5.4
    hooks:
    # linter.
    - id: ruff
      types_or: [ python, pyi, jupyter ]
    # formatter.
    - id: ruff-format
      types_or: [ python, pyi, jupyter ]
-   repo: https://github.com/econchick/interrogate
    rev: 1.7.0
    hooks:
     # docstring coverage
    - id: interrogate
      args: [-vv, --fail-under=80, -c, pyproject.toml]
      pass_filenames: false


## Uncomment mypy for type-checking errors in pre-commit

# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v1.5.0
#     hooks:
#       - id: mypy
#         additional_dependencies: [tokenize-rt==3.2.0, 'types-PyYAML']
#         exclude: ^tests/
#         args:
#           [
#               "--ignore-missing-imports",
#               "--check-untyped-defs",
#               "--warn-redundant-casts",
#               "--no-implicit-optional",
#               "--warn-return-any"
#           ]
